import type { LibrarySectionSchema } from "../types";

const item = (i: number) => ({
  id: `item_${i}`,
  type: "text" as const,
  label: `Line ${i}`,
  locales: { ar: { label: `السطر ${i}` } },
  default: "",
});

export const marqueeSchema: LibrarySectionSchema = {
  type: "lib-marquee",
  name: "Scrolling text",
  name_ar: "شريط كلام متحرك",
  locales: { en: { name: "Scrolling text" }, ar: { name: "شريط كلام متحرك" } },
  settings: [
    {
      id: "style",
      type: "select",
      label: "Style",
      locales: { ar: { label: "الشكل" } },
      default: "band",
      options: [
        { value: "band", label: "Band — short lines on a coloured strip", label_ar: "شريط ملوّن بجمل قصيرة" },
        { value: "statement", label: "Statement — one big quiet sentence", label_ar: "جملة واحدة كبيرة وهادية" },
        { value: "tilted", label: "Tilted tape — bold and playful", label_ar: "شريط مايل وجريء" },
      ],
    },
    { type: "header", content: "Text", locales: { ar: { content: "الكلام" } } },
    item(1),
    item(2),
    item(3),
    item(4),
    item(5),
    item(6),
    {
      id: "separator",
      type: "select",
      label: "Between lines",
      locales: { ar: { label: "الفاصل بين الجمل" } },
      default: "dot",
      options: [
        { value: "dot", label: "•", label_ar: "•" },
        { value: "star", label: "★", label_ar: "★" },
        { value: "diamond", label: "◆", label_ar: "◆" },
        { value: "slash", label: "/", label_ar: "/" },
        { value: "dash", label: "—", label_ar: "—" },
        { value: "none", label: "Nothing", label_ar: "من غير فاصل" },
      ],
    },
    { id: "link_url", type: "url", label: "Link (optional)", locales: { ar: { label: "لينك (اختياري)" } }, default: "" },
    { type: "header", content: "Look", locales: { ar: { content: "الشكل" } } },
    {
      id: "color_scheme",
      type: "select",
      label: "Colours",
      info: "Uses your theme's colours.",
      locales: { ar: { label: "الألوان", info: "بياخد ألوان الثيم بتاعك." } },
      default: "accent",
      options: [
        { value: "accent", label: "Accent strip", label_ar: "شريط بلون الثيم المميز" },
        { value: "ink", label: "Dark strip", label_ar: "شريط غامق" },
        { value: "light", label: "Light strip", label_ar: "شريط فاتح" },
        { value: "none", label: "No background", label_ar: "من غير خلفية" },
      ],
    },
    {
      id: "size",
      type: "select",
      label: "Text size",
      locales: { ar: { label: "حجم الكلام" } },
      default: "sm",
      options: [
        { value: "sm", label: "Small", label_ar: "صغير" },
        { value: "md", label: "Medium", label_ar: "متوسط" },
        { value: "lg", label: "Large", label_ar: "كبير" },
        { value: "xl", label: "Extra large", label_ar: "كبير جدًا" },
      ],
    },
    { id: "show_borders", type: "checkbox", label: "Lines above and below", locales: { ar: { label: "خط فوق وتحت" } }, default: false },
    { id: "padding_y", type: "range", label: "Height padding", locales: { ar: { label: "المسافة فوق وتحت" } }, default: 12, min: 0, max: 64, step: 2, unit: "px" },
    { type: "header", content: "Motion", locales: { ar: { content: "الحركة" } } },
    {
      id: "direction",
      type: "select",
      label: "Direction",
      locales: { ar: { label: "الاتجاه" } },
      default: "left",
      options: [
        { value: "left", label: "To the left", label_ar: "ناحية الشمال" },
        { value: "right", label: "To the right", label_ar: "ناحية اليمين" },
      ],
    },
    {
      id: "speed_seconds",
      type: "range",
      label: "One loop takes",
      info: "Higher is slower.",
      locales: { ar: { label: "اللفة الواحدة بتاخد", info: "الرقم الأكبر أبطأ." } },
      default: 30,
      min: 5,
      max: 120,
      step: 5,
      unit: "s",
    },
    { id: "pause_on_hover", type: "checkbox", label: "Pause when hovered", locales: { ar: { label: "يقف لما الماوس يعدّي عليه" } }, default: true },
  ],
  presets: [
    {
      name: "Scrolling text",
      category: "marketing",
      locales: { en: { name: "Scrolling text" }, ar: { name: "شريط كلام متحرك" } },
      settings: {},
    },
  ],
};
