import type { LibrarySectionSchema } from "../types";

const image = (id: string, label: string, labelAr: string, info?: [string, string]) => ({
  id,
  type: "image_picker" as const,
  label,
  ...(info ? { info: info[0] } : {}),
  locales: { ar: { label: labelAr, ...(info ? { info: info[1] } : {}) } },
  default: "",
});

export const heroSchema: LibrarySectionSchema = {
  type: "lib-hero",
  name: "Hero",
  name_ar: "البانر الرئيسي",
  locales: { en: { name: "Hero" }, ar: { name: "البانر الرئيسي" } },
  settings: [
    {
      id: "style",
      type: "select",
      label: "Style",
      locales: { ar: { label: "الشكل" } },
      default: "full",
      options: [
        { value: "full", label: "Full image — text over the photo", label_ar: "صورة كاملة والكلام فوقها" },
        { value: "split", label: "Split — photo beside a text panel", label_ar: "نصّين: صورة وجنبها الكلام" },
        { value: "slideshow", label: "Slideshow — several slides that change", label_ar: "سلايدر: كذا شريحة بيتغيّروا" },
        { value: "minimal", label: "Minimal — big headline, small photo", label_ar: "بسيط: عنوان كبير وصورة صغيرة" },
      ],
    },
    {
      type: "paragraph",
      content: "Add slides as blocks. Every style except Slideshow shows the first slide only.",
      locales: { ar: { content: "ضيف الشرايح من البلوكات. كل الأشكال ما عدا السلايدر بتعرض أول شريحة بس." } },
    },
    {
      id: "height",
      type: "select",
      label: "Height",
      locales: { ar: { label: "الارتفاع" } },
      default: "large",
      options: [
        { value: "medium", label: "Medium", label_ar: "متوسط" },
        { value: "large", label: "Large", label_ar: "كبير" },
        { value: "screen", label: "Full screen", label_ar: "الشاشة كلها" },
      ],
    },
    {
      id: "text_align",
      type: "select",
      label: "Text alignment",
      locales: { ar: { label: "محاذاة الكلام" } },
      default: "center",
      options: [
        { value: "start", label: "Start", label_ar: "ناحية البداية" },
        { value: "center", label: "Centre", label_ar: "في النص" },
        { value: "end", label: "End", label_ar: "ناحية النهاية" },
      ],
    },
    {
      id: "overlay_opacity",
      type: "range",
      label: "Image darkening",
      info: "Full image and Slideshow. Makes the text easier to read.",
      locales: { ar: { label: "تغميق الصورة", info: "في الصورة الكاملة والسلايدر. بيخلّي الكلام أوضح." } },
      default: 30,
      min: 0,
      max: 80,
      step: 5,
      unit: "%",
    },
    { type: "header", content: "Slideshow", locales: { ar: { content: "السلايدر" } } },
    {
      id: "autoplay",
      type: "checkbox",
      label: "Change slides automatically",
      info: "Stops while a shopper hovers or uses the keyboard, and for anyone who turned on reduced motion.",
      locales: { ar: { label: "الشرايح تتغيّر لوحدها", info: "بتقف لما حد يعدّي بالماوس أو يستخدم الكيبورد، ولأي حد مشغّل تقليل الحركة على جهازه." } },
      default: true,
    },
    {
      id: "interval",
      type: "range",
      label: "Seconds per slide",
      locales: { ar: { label: "ثواني كل شريحة" } },
      default: 6,
      min: 3,
      max: 12,
      step: 1,
      unit: "s",
    },
    { type: "header", content: "Split", locales: { ar: { content: "شكل النصّين" } } },
    {
      id: "image_side",
      type: "select",
      label: "Image side",
      locales: { ar: { label: "مكان الصورة" } },
      default: "end",
      options: [
        { value: "start", label: "Start", label_ar: "ناحية البداية" },
        { value: "end", label: "End", label_ar: "ناحية النهاية" },
      ],
    },
  ],
  blocks: [
    {
      type: "slide",
      name: "Slide",
      name_ar: "شريحة",
      locales: { en: { name: "Slide" }, ar: { name: "شريحة" } },
      settings: [
        image("image", "Image (desktop)", "الصورة (كمبيوتر)"),
        image("image_mobile", "Image (mobile)", "الصورة (موبايل)", [
          "Optional taller crop for phones.",
          "اختياري: صورة طولية تناسب شاشة الموبايل.",
        ]),
        { id: "eyebrow", type: "text", label: "Small line above the headline", locales: { ar: { label: "سطر صغير فوق العنوان" } }, default: "" },
        { id: "headline", type: "text", label: "Headline", locales: { ar: { label: "العنوان" } }, default: "" },
        { id: "subheading", type: "textarea", label: "Subheading", locales: { ar: { label: "الكلام تحت العنوان" } }, default: "" },
        { id: "cta_text", type: "text", label: "Button text", locales: { ar: { label: "كلام الزرار" } }, default: "" },
        { id: "cta_link", type: "url", label: "Button link", locales: { ar: { label: "لينك الزرار" } }, default: "" },
        { id: "cta2_text", type: "text", label: "Second button text", locales: { ar: { label: "كلام الزرار التاني" } }, default: "" },
        { id: "cta2_link", type: "url", label: "Second button link", locales: { ar: { label: "لينك الزرار التاني" } }, default: "" },
        {
          id: "text_color",
          type: "select",
          label: "Text colour",
          info: "Full image and Slideshow. Pick what stays readable on this photo.",
          locales: { ar: { label: "لون الكلام", info: "في الصورة الكاملة والسلايدر. اختار اللون اللي يبان واضح على الصورة دي." } },
          default: "light",
          options: [
            { value: "light", label: "Light", label_ar: "فاتح" },
            { value: "dark", label: "Dark", label_ar: "غامق" },
          ],
        },
      ],
    },
  ],
  max_blocks: 5,
  presets: [
    {
      name: "Hero",
      category: "hero",
      locales: { en: { name: "Hero" }, ar: { name: "البانر الرئيسي" } },
      settings: {},
      blocks: [{ type: "slide", settings: {} }],
    },
  ],
};
