import type { LibrarySectionSchema } from "../types";

export const promoBannerSchema: LibrarySectionSchema = {
  type: "lib-promo-banner",
  name: "Promo banner",
  name_ar: "بانر إعلاني",
  locales: { en: { name: "Promo banner" }, ar: { name: "بانر إعلاني" } },
  settings: [
    {
      id: "style",
      type: "select",
      label: "Style",
      locales: { ar: { label: "الشكل" } },
      default: "photo",
      options: [
        { value: "photo", label: "Photo — one wide image, little text", label_ar: "صورة عريضة وكلام قليل" },
        { value: "split", label: "Offer card — badge, headline and image side by side", label_ar: "كارت عرض: شارة وعنوان وصورة جنب بعض" },
      ],
    },
    {
      type: "paragraph",
      content: "Photo: one wide photograph, edge to edge — the less on top of it, the better. Offer card: a clear offer with a button.",
      locales: { ar: { content: "الصورة: صورة واحدة عريضة من الطرف للطرف، وكل ما تحط عليها حاجات أقل كل ما تبان أحلى. كارت العرض: عرض واضح وجنبه زرار." } },
    },
    { id: "image", type: "image_picker", label: "Image (desktop)", locales: { ar: { label: "الصورة (كمبيوتر)" } }, default: "" },
    {
      id: "image_mobile",
      type: "image_picker",
      label: "Image (mobile)",
      info: "Optional taller crop for phones. Photo style only.",
      locales: { ar: { label: "الصورة (موبايل)", info: "اختياري: صورة طولية تناسب شاشة الموبايل. في شكل الصورة بس." } },
      default: "",
    },
    {
      id: "overlay_text",
      type: "text",
      label: "Headline",
      info: "Photo style: leave empty for a clean photo with no overlay.",
      locales: { ar: { label: "العنوان", info: "في شكل الصورة: سيبه فاضي علشان الصورة تفضل نضيفة من غير أي طبقة فوقها." } },
      default: "",
    },
    {
      id: "badge_text",
      type: "text",
      label: "Badge",
      info: "Offer card only, e.g. \"Limited time\".",
      locales: { ar: { label: "الشارة", info: "في كارت العرض بس، مثلًا «لفترة محدودة»." } },
      default: "",
    },
    {
      id: "subtitle",
      type: "textarea",
      label: "Subtitle",
      info: "Offer card only.",
      locales: { ar: { label: "سطر تحت العنوان", info: "في كارت العرض بس." } },
      default: "",
    },
    { id: "cta_text", type: "text", label: "Button text", locales: { ar: { label: "كلام الزرار" } }, default: "" },
    { id: "cta_link", type: "url", label: "Button link", locales: { ar: { label: "لينك الزرار" } }, default: "/products" },
    { type: "header", content: "Photo style", locales: { ar: { content: "شكل الصورة" } } },
    {
      id: "height",
      type: "select",
      label: "Height",
      locales: { ar: { label: "الارتفاع" } },
      default: "medium",
      options: [
        { value: "short", label: "Short", label_ar: "قصير" },
        { value: "medium", label: "Medium", label_ar: "متوسط" },
        { value: "tall", label: "Tall", label_ar: "طويل" },
      ],
    },
    { id: "full_width", type: "checkbox", label: "Full width", locales: { ar: { label: "بعرض الشاشة كلها" } }, default: true },
    {
      id: "text_position",
      type: "select",
      label: "Text position",
      locales: { ar: { label: "مكان الكلام" } },
      default: "center",
      options: [
        { value: "center", label: "Centre", label_ar: "في النص" },
        { value: "bottom-start", label: "Bottom, start side", label_ar: "تحت ناحية البداية" },
        { value: "bottom-end", label: "Bottom, end side", label_ar: "تحت ناحية النهاية" },
      ],
    },
    {
      id: "overlay_opacity",
      type: "range",
      label: "Image darkening",
      info: "Only applies when there is text on the image.",
      locales: { ar: { label: "تغميق الصورة", info: "بيتطبق بس لما يكون فيه كلام على الصورة." } },
      default: 20,
      min: 0,
      max: 70,
      step: 5,
      unit: "%",
    },
  ],
  presets: [
    {
      name: "Promo banner",
      category: "marketing",
      locales: { en: { name: "Promo banner" }, ar: { name: "بانر إعلاني" } },
      settings: {},
    },
  ],
};
