import type { LibrarySectionSchema } from "../types";

export const productRailSchema: LibrarySectionSchema = {
  type: "lib-product-rail",
  name: "Products",
  name_ar: "منتجات",
  locales: { en: { name: "Products" }, ar: { name: "منتجات" } },
  settings: [
    { id: "heading", type: "text", label: "Heading", locales: { ar: { label: "العنوان" } }, default: "" },
    { id: "subheading", type: "text", label: "Text under the heading", locales: { ar: { label: "الكلام اللي تحت العنوان" } }, default: "" },
    { type: "header", content: "Products", locales: { en: { content: "Products" }, ar: { content: "المنتجات" } } },
    {
      id: "source",
      type: "select",
      label: "Which products",
      info: "Stores with more than 100 products may see some missing from a collection or tag.",
      locales: {
        ar: {
          label: "المنتجات اللي تظهر",
          info: "لو متجرك فيه أكتر من 100 منتج، ممكن شوية منتجات من التصنيف أو التاج ما يظهروش.",
        },
      },
      default: "newest",
      options: [
        { value: "newest", label: "Newest", label_ar: "الأحدث" },
        { value: "collection", label: "From a collection", label_ar: "من تصنيف" },
        { value: "tag", label: "With a tag", label_ar: "بتاج معيّن" },
        { value: "product_list", label: "Products I pick", label_ar: "منتجات بتختارها بنفسك" },
      ],
    },
    {
      id: "collection",
      type: "collection",
      label: "Collection",
      info: "Used when \"From a collection\" is picked.",
      locales: { ar: { label: "التصنيف", info: "بيتستخدم لما تختار «من تصنيف»." } },
    },
    {
      id: "tag",
      type: "text",
      label: "Tag",
      info: "Used when \"With a tag\" is picked.",
      locales: { ar: { label: "التاج", info: "بيتستخدم لما تختار «بتاج معيّن»." } },
      default: "",
    },
    {
      id: "product_list",
      type: "product_list",
      label: "Products",
      info: "Used when \"Products I pick\" is picked. Shown in this order.",
      locales: { ar: { label: "المنتجات", info: "بيتستخدم لما تختار «منتجات بتختارها بنفسك»، وبتظهر بنفس الترتيب." } },
    },
    {
      id: "limit",
      type: "range",
      label: "How many products",
      locales: { ar: { label: "عدد المنتجات" } },
      default: 8,
      min: 2,
      max: 24,
      step: 1,
    },
    { type: "header", content: "Layout", locales: { en: { content: "Layout" }, ar: { content: "الشكل" } } },
    {
      id: "style",
      type: "select",
      label: "Style",
      locales: { ar: { label: "طريقة العرض" } },
      default: "rail",
      options: [
        { value: "rail", label: "Rail — scrolls sideways", label_ar: "شريط بيتحرّك بالعرض" },
        { value: "grid", label: "Grid", label_ar: "شبكة" },
      ],
    },
    {
      id: "columns_desktop",
      type: "range",
      label: "Products per row (desktop)",
      locales: { ar: { label: "عدد المنتجات في الصف (كمبيوتر)" } },
      default: 4,
      min: 2,
      max: 6,
      step: 1,
    },
    {
      id: "columns_mobile",
      type: "range",
      label: "Products per row (phone)",
      locales: { ar: { label: "عدد المنتجات في الصف (موبايل)" } },
      default: 2,
      min: 1,
      max: 2,
      step: 1,
    },
    {
      id: "image_ratio",
      type: "select",
      label: "Image shape",
      locales: { ar: { label: "شكل الصورة" } },
      default: "3-4",
      options: [
        { value: "3-4", label: "Portrait (3:4)", label_ar: "طولي (3:4)" },
        { value: "1-1", label: "Square (1:1)", label_ar: "مربع (1:1)" },
        { value: "4-5", label: "Portrait (4:5)", label_ar: "طولي (4:5)" },
      ],
    },
    {
      id: "show_quick_add",
      type: "checkbox",
      label: "Show \"Add to bag\" button",
      locales: { ar: { label: "اظهر زرار «أضف للسلة»" } },
      default: true,
    },
    {
      id: "show_discount_badge",
      type: "checkbox",
      label: "Show discount percentage",
      locales: { ar: { label: "اظهر نسبة الخصم" } },
      default: true,
    },
    {
      id: "view_all_label",
      type: "text",
      label: "\"View all\" text",
      locales: { ar: { label: "كلام لينك «شوف الكل»" } },
      default: "",
    },
    {
      id: "view_all_link",
      type: "url",
      label: "\"View all\" link",
      info: "Leave empty to hide the link.",
      locales: { ar: { label: "لينك «شوف الكل»", info: "سيبه فاضي لو مش عايز اللينك يظهر." } },
      default: "/products",
    },
  ],
  presets: [
    {
      name: "Products",
      category: "products",
      locales: { en: { name: "Products" }, ar: { name: "منتجات" } },
      settings: {},
    },
  ],
};
